import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { Button } from 'react-bootstrap'
import styles from '../styles/Home.module.css'



import { AiOutlinePlus ,AiOutlineMinus, AiFillHeart } from 'react-icons/ai'
import { MdOutlineAddShoppingCart } from 'react-icons/md'



export default function Home({ data }) {
const [count, seCount] = useState(1)

  console.log(data.data, 'dd')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home-page d-flex justify-content-center align-items-center">

        <div className="box-container  w-100">
          <div className="content px-2 pb-3">
          <div className="container">
            <div className="row">
              {data.data.map(dt => (
                <div key={dt.id} className="col-md-6">
                  <div className="content">
                    <Image
                      width="400px"
                      height="250px"
                      src={dt.prize_id.image}
                      className="text-center"
                    />
                    <h1 className="title text-center">{dt.prize_id.name}</h1>
                    <p className="description text-center">{dt.prize_id.description}</p>

                  </div>
                </div>

              ))}
            </div>
          </div>
          {/* AED */}
          <div className="aed">
            AED 50.00
          </div>

          <div className="add-to d-flex justify-content-between flex-md-column flex-sm-row flex-column">
            <div className="add-to-fav d-flex justify-content-center align-items-center">
              <AiFillHeart color="white" size="1.5em" />
            </div>
            <div className="add-to-cart d-flex justify-content-center align-items-center">
              <MdOutlineAddShoppingCart color="white" size="1.5em"  />
            </div>
          </div>

          

          {/* progress */}
          <div className="progress-container">
            <div className="progress-bar">
              <div className="content">
                <div className="text p-2">
                  <h5 className="m-0">382</h5>
                  <h6 className="m-0">SOLD</h6>
                  <p>OUT OF <br /> 975</p>

                </div>
              </div>
            </div>

          </div>

          </div>

          {/* Plus and Minus section */}
          <div className="count-container d-flex flex-md-column flex-row  justify-content-md-center justify-content-between">
              <span  className="plus" onClick={()=> seCount(count++)}><AiOutlinePlus size="1.2em  " color="white"/></span>
              <span>
              {count}
              </span>
              <span className="minus" onClick={()=> seCount(count--)}> <AiOutlineMinus size="1.2em  " color="white" />  </span>
          </div>
          <Button className="border-0 mx-auto my-2 d-md-none d-flex">Show Your Cart</Button>
        </div>
      </div>

    </div>
  )
}

export async function getStaticProps(context) {
  // console.log('contextttttttttttttttttttttttttt about', context.locale)

  const response = await fetch('https://wawinner.its.ae/dev/public/api/v1/front-end/campaign')
  const data = await response.json()

  console.log('fffffffff', data)
  return {
    props: {
      data,
    },
    revalidate: 10000000,
  };
}